/**
 * karmacv-ws
 * Restful web service for resumes of resumerise app.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: eltonmarku@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export class CategoryKey {
    'award'?: string;
    'basic'?: string;
    'certificate'?: string;
    'education'?: string;
    'id'?: string;
    'interest'?: string;
    'language'?: string;
    'location'?: string;
    'profile'?: string;
    'project'?: string;
    'publication'?: string;
    'reference'?: string;
    'skill'?: string;
    'volunteer'?: string;
    'work'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "award",
            "baseName": "award",
            "type": "string"
        },
        {
            "name": "basic",
            "baseName": "basic",
            "type": "string"
        },
        {
            "name": "certificate",
            "baseName": "certificate",
            "type": "string"
        },
        {
            "name": "education",
            "baseName": "education",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "interest",
            "baseName": "interest",
            "type": "string"
        },
        {
            "name": "language",
            "baseName": "language",
            "type": "string"
        },
        {
            "name": "location",
            "baseName": "location",
            "type": "string"
        },
        {
            "name": "profile",
            "baseName": "profile",
            "type": "string"
        },
        {
            "name": "project",
            "baseName": "project",
            "type": "string"
        },
        {
            "name": "publication",
            "baseName": "publication",
            "type": "string"
        },
        {
            "name": "reference",
            "baseName": "reference",
            "type": "string"
        },
        {
            "name": "skill",
            "baseName": "skill",
            "type": "string"
        },
        {
            "name": "volunteer",
            "baseName": "volunteer",
            "type": "string"
        },
        {
            "name": "work",
            "baseName": "work",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CategoryKey.attributeTypeMap;
    }
}

