/**
 * karmacv-ws
 * Restful web service for resumes of resumerise app.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: eltonmarku@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { AwardLabel } from './awardLabel.ts';
import { BasicsLabel } from './basicsLabel.ts';
import { CertificationLabel } from './certificationLabel.ts';
import { EducationLabel } from './educationLabel.ts';
import { InterestLabel } from './interestLabel.ts';
import { LanguageLabel } from './languageLabel.ts';
import { LocationLabel } from './locationLabel.ts';
import { ProfileLabel } from './profileLabel.ts';
import { ProjectLabel } from './projectLabel.ts';
import { PublicationLabel } from './publicationLabel.ts';
import { ReferenceLabel } from './referenceLabel.ts';
import { SkillLabel } from './skillLabel.ts';
import { VolunteerLabel } from './volunteerLabel.ts';
import { WorkLabel } from './workLabel.ts';

export class CategoryProperty {
    'award'?: AwardLabel;
    'basics'?: BasicsLabel;
    'certificate'?: CertificationLabel;
    'education'?: EducationLabel;
    'id'?: string;
    'interest'?: InterestLabel;
    'language'?: LanguageLabel;
    'location'?: LocationLabel;
    'profile'?: ProfileLabel;
    'project'?: ProjectLabel;
    'publication'?: PublicationLabel;
    'reference'?: ReferenceLabel;
    'skill'?: SkillLabel;
    'volunteer'?: VolunteerLabel;
    'work'?: WorkLabel;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "award",
            "baseName": "award",
            "type": "AwardLabel"
        },
        {
            "name": "basics",
            "baseName": "basics",
            "type": "BasicsLabel"
        },
        {
            "name": "certificate",
            "baseName": "certificate",
            "type": "CertificationLabel"
        },
        {
            "name": "education",
            "baseName": "education",
            "type": "EducationLabel"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "interest",
            "baseName": "interest",
            "type": "InterestLabel"
        },
        {
            "name": "language",
            "baseName": "language",
            "type": "LanguageLabel"
        },
        {
            "name": "location",
            "baseName": "location",
            "type": "LocationLabel"
        },
        {
            "name": "profile",
            "baseName": "profile",
            "type": "ProfileLabel"
        },
        {
            "name": "project",
            "baseName": "project",
            "type": "ProjectLabel"
        },
        {
            "name": "publication",
            "baseName": "publication",
            "type": "PublicationLabel"
        },
        {
            "name": "reference",
            "baseName": "reference",
            "type": "ReferenceLabel"
        },
        {
            "name": "skill",
            "baseName": "skill",
            "type": "SkillLabel"
        },
        {
            "name": "volunteer",
            "baseName": "volunteer",
            "type": "VolunteerLabel"
        },
        {
            "name": "work",
            "baseName": "work",
            "type": "WorkLabel"
        }    ];

    static getAttributeTypeMap() {
        return CategoryProperty.attributeTypeMap;
    }
}

