/**
 * karmacv-ws
 * Restful web service for resumes of resumerise app.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: eltonmarku@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export class EducationLabel {
    'area'?: string;
    'categoryTitle'?: string;
    'courses'?: string;
    'gpa'?: string;
    'id'?: string;
    'institution'?: string;
    'studyType'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "area",
            "baseName": "area",
            "type": "string"
        },
        {
            "name": "categoryTitle",
            "baseName": "categoryTitle",
            "type": "string"
        },
        {
            "name": "courses",
            "baseName": "courses",
            "type": "string"
        },
        {
            "name": "gpa",
            "baseName": "gpa",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "institution",
            "baseName": "institution",
            "type": "string"
        },
        {
            "name": "studyType",
            "baseName": "studyType",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return EducationLabel.attributeTypeMap;
    }
}

