/**
 * karmacv-ws
 * Restful web service for resumes of resumerise app.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: eltonmarku@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Award } from './award.ts';
import { Basics } from './basics.ts';
import { Certification } from './certification.ts';
import { Education } from './education.ts';
import { Interest } from './interest.ts';
import { Language } from './language.ts';
import { Project } from './project.ts';
import { Publication } from './publication.ts';
import { Reference } from './reference.ts';
import { Settings } from './settings.ts';
import { Skill } from './skill.ts';
import { Volunteer } from './volunteer.ts';
import { Widget } from './widget.ts';
import { Work } from './work.ts';

/**
* The resume class
*/
export class Resume {
    'awards'?: Array<Award>;
    'basics'?: Basics;
    'certifications'?: Array<Certification>;
    'created'?: Date;
    'education'?: Array<Education>;
    'id'?: string;
    'interests'?: Array<Interest>;
    'languages'?: Array<Language>;
    /**
    * last synchronize date
    */
    'lastSync'?: Date;
    'picture'?: string;
    'privacyMode'?: Resume.PrivacyModeEnum;
    'projects'?: Array<Project>;
    'publications'?: Array<Publication>;
    'references'?: Array<Reference>;
    'settings'?: Settings;
    'skills'?: Array<Skill>;
    'syncConflictStatus'?: Resume.SyncConflictStatusEnum;
    'themeName'?: string;
    'updated'?: Date;
    'visibleLink'?: boolean;
    'volunteer'?: Array<Volunteer>;
    'widgets'?: Array<Widget>;
    'work'?: Array<Work>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "awards",
            "baseName": "awards",
            "type": "Array<Award>"
        },
        {
            "name": "basics",
            "baseName": "basics",
            "type": "Basics"
        },
        {
            "name": "certifications",
            "baseName": "certifications",
            "type": "Array<Certification>"
        },
        {
            "name": "created",
            "baseName": "created",
            "type": "Date"
        },
        {
            "name": "education",
            "baseName": "education",
            "type": "Array<Education>"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "interests",
            "baseName": "interests",
            "type": "Array<Interest>"
        },
        {
            "name": "languages",
            "baseName": "languages",
            "type": "Array<Language>"
        },
        {
            "name": "lastSync",
            "baseName": "lastSync",
            "type": "Date"
        },
        {
            "name": "picture",
            "baseName": "picture",
            "type": "string"
        },
        {
            "name": "privacyMode",
            "baseName": "privacyMode",
            "type": "Resume.PrivacyModeEnum"
        },
        {
            "name": "projects",
            "baseName": "projects",
            "type": "Array<Project>"
        },
        {
            "name": "publications",
            "baseName": "publications",
            "type": "Array<Publication>"
        },
        {
            "name": "references",
            "baseName": "references",
            "type": "Array<Reference>"
        },
        {
            "name": "settings",
            "baseName": "settings",
            "type": "Settings"
        },
        {
            "name": "skills",
            "baseName": "skills",
            "type": "Array<Skill>"
        },
        {
            "name": "syncConflictStatus",
            "baseName": "syncConflictStatus",
            "type": "Resume.SyncConflictStatusEnum"
        },
        {
            "name": "themeName",
            "baseName": "themeName",
            "type": "string"
        },
        {
            "name": "updated",
            "baseName": "updated",
            "type": "Date"
        },
        {
            "name": "visibleLink",
            "baseName": "visibleLink",
            "type": "boolean"
        },
        {
            "name": "volunteer",
            "baseName": "volunteer",
            "type": "Array<Volunteer>"
        },
        {
            "name": "widgets",
            "baseName": "widgets",
            "type": "Array<Widget>"
        },
        {
            "name": "work",
            "baseName": "work",
            "type": "Array<Work>"
        }    ];

    static getAttributeTypeMap() {
        return Resume.attributeTypeMap;
    }
}

export namespace Resume {
    export enum PrivacyModeEnum {
        Closed = <any> 'CLOSED',
        Open = <any> 'OPEN'
    }
    export enum SyncConflictStatusEnum {
        Conflict = <any> 'CONFLICT',
        TakeClient = <any> 'TAKE_CLIENT',
        TakeServer = <any> 'TAKE_SERVER'
    }
}
