/**
 * karmacv-ws
 * Restful web service for resumes of resumerise app.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: eltonmarku@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CategoryKey } from './categoryKey.ts';
import { ThemeLabel } from './themeLabel.ts';

export class Settings {
    'categoryKey'?: CategoryKey;
    'dateFormat'?: string;
    'id'?: string;
    'labels'?: ThemeLabel;
    'visibleCategories'?: Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "categoryKey",
            "baseName": "categoryKey",
            "type": "CategoryKey"
        },
        {
            "name": "dateFormat",
            "baseName": "dateFormat",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "labels",
            "baseName": "labels",
            "type": "ThemeLabel"
        },
        {
            "name": "visibleCategories",
            "baseName": "visibleCategories",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return Settings.attributeTypeMap;
    }
}

