/**
 * karmacv-ws
 * Restful web service for resumes of resumerise app.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: eltonmarku@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CategoryProperty } from './categoryProperty.ts';
import { GeneralLabel } from './generalLabel.ts';

export class ThemeLabel {
    'categoryProperty'?: CategoryProperty;
    'general'?: GeneralLabel;
    'id'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "categoryProperty",
            "baseName": "categoryProperty",
            "type": "CategoryProperty"
        },
        {
            "name": "general",
            "baseName": "general",
            "type": "GeneralLabel"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ThemeLabel.attributeTypeMap;
    }
}

